"""Add target_bookmaker

Revision ID: 9e344607e0e5
Revises: 0001_initial
Create Date: 2026-07-16 12:15:33.648822
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9e344607e0e5'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('actual_edge', sa.Float(), nullable=True))
    op.add_column('bets', sa.Column('clv', sa.Float(), nullable=True))
    op.alter_column('bets', 'signal_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('bets', 'book',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'stoiximan'::character varying"))
    op.alter_column('bets', 'selection',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('bets', 'placed_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bets', 'stake',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bets', 'outcome',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bets', 'dry_run',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('bets', 'placed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'sport',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_events_betfair_event_id'), 'events', ['betfair_event_id'], unique=False)
    op.create_index(op.f('ix_events_pinnacle_event_id'), 'events', ['pinnacle_event_id'], unique=False)
    op.alter_column('markets', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('markets', 'market_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('markets', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'prematch'::character varying"))
    op.create_index(op.f('ix_markets_betfair_market_id'), 'markets', ['betfair_market_id'], unique=False)
    op.add_column('odds_snapshot', sa.Column('lay_odds', sa.Float(), nullable=True))
    op.add_column('odds_snapshot', sa.Column('back_liquidity', sa.Float(), nullable=True))
    op.add_column('odds_snapshot', sa.Column('lay_liquidity', sa.Float(), nullable=True))
    op.add_column('odds_snapshot', sa.Column('total_matched', sa.Float(), nullable=True))
    op.alter_column('odds_snapshot', 'decimal_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('odds_snapshot_captured_at_idx'), table_name='odds_snapshot')
    op.create_index(op.f('ix_odds_snapshot_source'), 'odds_snapshot', ['source'], unique=False)
    op.drop_column('odds_snapshot', 'liquidity')
    op.alter_column('signals', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('signals', 'market_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('signals', 'selection',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('signals', 'sport',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('signals', 'fair_prob',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'target_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'edge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'recommended_stake',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('signals', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'detected'::character varying"))
    op.alter_column('signals', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'detected_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('signals', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'detected'::character varying"))
    op.alter_column('signals', 'recommended_stake',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('signals', 'edge',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('signals', 'target_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('signals', 'fair_prob',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('signals', 'sport',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('signals', 'selection',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('signals', 'market_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('signals', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('odds_snapshot', sa.Column('liquidity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_odds_snapshot_source'), table_name='odds_snapshot')
    op.create_index(op.f('odds_snapshot_captured_at_idx'), 'odds_snapshot', [sa.literal_column('captured_at DESC')], unique=False)
    op.alter_column('odds_snapshot', 'decimal_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('odds_snapshot', 'total_matched')
    op.drop_column('odds_snapshot', 'lay_liquidity')
    op.drop_column('odds_snapshot', 'back_liquidity')
    op.drop_column('odds_snapshot', 'lay_odds')
    op.drop_index(op.f('ix_markets_betfair_market_id'), table_name='markets')
    op.alter_column('markets', 'status',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'prematch'::character varying"))
    op.alter_column('markets', 'market_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('markets', 'event_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_events_pinnacle_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_betfair_event_id'), table_name='events')
    op.alter_column('events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('events', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('events', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('events', 'sport',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('bets', 'placed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bets', 'dry_run',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('bets', 'outcome',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('bets', 'stake',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bets', 'placed_odds',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bets', 'selection',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('bets', 'book',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'stoiximan'::character varying"))
    op.alter_column('bets', 'signal_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('bets', 'clv')
    op.drop_column('bets', 'actual_edge')
    # ### end Alembic commands ###
